"""delete

Revision ID: 9c1bc9cf2e70
Revises: ee44fd793a05
Create Date: 2025-04-01 00:12:52.163939

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c1bc9cf2e70"
down_revision: Union[str, None] = "ee44fd793a05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("bookings_room_id_fkey", "bookings", type_="foreignkey")
    op.create_foreign_key(
        None, "bookings", "rooms", ["room_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.create_foreign_key(
        "bookings_room_id_fkey", "bookings", "rooms", ["room_id"], ["id"]
    )
    # ### end Alembic commands ###
