"""fix

Revision ID: 51acbbd5bb77
Revises: 4c903b896b24
Create Date: 2025-01-27 19:38:56.657163

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51acbbd5bb77"
down_revision: Union[str, None] = "4c903b896b24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=200), nullable=False)
    )
    op.add_column("users", sa.Column("login", sa.String(length=200), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(length=200), nullable=False))
    op.drop_column("users", "passowrd")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "passowrd", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "password")
    op.drop_column("users", "login")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
