"""delete

Revision ID: 07f3c50ae486
Revises: 9c1bc9cf2e70
Create Date: 2025-04-01 00:13:15.721470

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "07f3c50ae486"
down_revision: Union[str, None] = "9c1bc9cf2e70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("rooms_hotel_id_fkey", "rooms", type_="foreignkey")
    op.create_foreign_key(None, "rooms", "hotels", ["hotel_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rooms", type_="foreignkey")
    op.create_foreign_key(
        "rooms_hotel_id_fkey",
        "rooms",
        "hotels",
        ["hotel_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
