"""unique columns

Revision ID: eeb107ee34dc
Revises: a2166a078473
Create Date: 2025-01-27 23:43:04.789784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eeb107ee34dc"
down_revision: Union[str, None] = "a2166a078473"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["login"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
